version: '3.7'

networks:
  default:
    driver: bridge

services:

  php:
    image: likesistemas/php-dev:${PHP_VERSION:-56}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
    volumes:
      - ./:/var/www/public/
    networks:
      - default
